name: prajalok
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.4
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_dotenv: ^5.1.0
  timeago: any
  supabase_flutter: 
  get_storage: ^2.1.1
  animated_custom_dropdown: any
  sms_autofill: ^2.3.0
  pretty_dio_logger: any
  logger: any
  google_fonts: any
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  permission_handler: any
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  flutter_staggered_grid_view: ^0.7.0
  auto_size_text: ^3.0.0
  r_dotted_line_border: any
  file_picker: any
  image_picker: ^1.0.4
  dio: ^5.4.0
  mime: ^1.0.4
  http: ^0.13.6
  flutter_timer_countdown: ^1.0.7
  web_socket_channel: ^2.4.0
  lottie: ^2.7.0
  flutter_markdown: ^0.6.18+2
  syncfusion_flutter_pdfviewer: any
  syncfusion_flutter_core: any
  carousel_slider: any
  flutter_advanced_drawer: any
  readmore: ^2.2.0
  drop_down_list: any
  percent_indicator: ^4.2.3
  cached_network_image: ^3.3.1
  any_link_preview: any
  share_plus: ^7.2.2
  photo_view: ^0.14.0
  dotted_border: ^2.1.0
  connectivity_plus: ^5.0.2
  razorpay_flutter: ^1.3.6
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - .env
    - assets/images/
    - assets/icons/

  uses-material-design: true

  fonts: 
    - family: OpenSans
      fonts: 
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf

